stages:
  - build
  - test

image: garrettwrong/cql3d_f90_centos-7

build:centos7:
  stage: build
  script:
  - make -f  makefile_gfortran64.CentOS7
  artifacts:
    paths:
    - xcql3d_gfortran64
    expire_in: 1 week

case1:
  stage: test
  script:
  - cd ci/case1
  - ../../xcql3d_gfortran64
  - nccmp -dmgfs reference.nc mst_stand_lh00001.MergedCQL3D_direct_lh-dis.nc
  dependencies:
  - build:centos7
