# Copyright 2019 Garrett Wright, Princeton Plasma Physics Laboratory,
#    contracted by the U.S. Department of Energy (putnumberhere).
#
# This file is part of cql3d_f90. See LICENSE.
#
# cql3d_f90 is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cql3d_f90 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cql3d_f90.  If not, see <https://www.gnu.org/licenses/>.


stages:
  - lint
  - build
  - test

checkbadchars:
  stage: lint
  script: >
    test $(grep -caxv '.*' *.f *.f90 *.h *.h77 README* LICENSE* cqlinput* CQL3D_users.txt eqdsk |
    cut -d: -f2 | awk '{ SUM += $1} END { print SUM }') -eq 0

enforce_unixish:
  stage: lint
  script: test $(file -k  *.f *.f90 *.h *.h77 README* LICENSE* cqlinput* CQL3D_users.txt eqdsk | grep -c "CRLF") -eq 0

build:centos7:
  stage: build
  image: garrettwrong/cql3d_f90_centos-7
  script:
  - make -f  makefile_gfortran64.CentOS7 all
  artifacts:
    paths:
    - xcql3d
    - xcql3d_shared
    - libxcql3d.so
    - libxcql3d.a
    expire_in: 1 week

case1:
  stage: test
  image: garrettwrong/cql3d_f90_centos-7
  script:
  - cd ci/case1
  - ../../xcql3d
  - nccmp -dmgfs reference.nc mst_stand_lh00001.MergedCQL3D_direct_lh-dis.nc
  artifacts:
    when: always
    paths:
    - ci/case1/mst_stand_lh00001.MergedCQL3D_direct_lh-dis.nc
    - ci/case1/mst_stand_lh00001.MergedCQL3D_direct_lh-dis.ps
    expire_in: 1 week
  dependencies:
  - build:centos7

case1_shared:
  stage: test
  image: garrettwrong/cql3d_f90_centos-7
  script:
  - export LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH
  - cd ci/case1
  - ../../xcql3d_shared
  - nccmp -dmgfs reference.nc mst_stand_lh00001.MergedCQL3D_direct_lh-dis.nc
  artifacts:
    when: always
    paths:
    - ci/case1/mst_stand_lh00001.MergedCQL3D_direct_lh-dis.nc
    - ci/case1/mst_stand_lh00001.MergedCQL3D_direct_lh-dis.ps
    expire_in: 1 week
  dependencies:
  - build:centos7

nstx_NBI_urf:
  stage: test
  image: garrettwrong/cql3d_f90_centos-7
  script:
  - cd ci/nstx_NBI_urf
  - ../../xcql3d
  - nccmp -dmgfs nstx_130608.00352.0_short_rerun190612.nc reference.nc
  - nccmp -dmgfs nstx_130608.00352.0_short_rerun190612_krf001.nc reference_krf001.nc 
  artifacts:
    when: always
    paths:
    - ci/nstx_NBI_urf/nstx_130608.00352.0_short_rerun190612.nc
    - ci/nstx_NBI_urf/nstx_130608.00352.0_short_rerun190612_krf001.nc
    - ci/nstx_NBI_urf/nstx_130608.00352.0_short_rerun190612.ps
    expire_in: 1 week
  dependencies:
  - build:centos7

ampere_faraday:
  stage: test
  image: garrettwrong/cql3d_f90_centos-7
  script:
  - cd ci/ampere_faraday
  - ../../xcql3d
  - nccmp -dmgfs reference.nc freidberg_full_eps_AF_3rd_root_J0.3.3_nstop10_lrz20.nc
  artifacts:
    when: always
    paths:
    - ci/ampere_faraday/freidberg_full_eps_AF_3rd_root_J0.3.3_nstop10_lrz20.nc
    - ci/ampere_faraday/freidberg_full_eps_AF_3rd_root_J0.3.3_nstop10_lrz20.ps
    expire_in: 1 week
  dependencies:
  - build:centos7

amp_far_rune_knockon:
  stage: test
  image: garrettwrong/cql3d_f90_centos-7
  script:
  - cd ci/amp_far_rune_knockon
  - ../../xcql3d
  - nccmp -dmgfs reference.nc tdep_ko_amp-far.4.3_short_test.nc
  artifacts:
    when: always
    paths:
    - ci/amp_far_rune_knockon/tdep_ko_amp-far.4.3_short_test.nc
    - ci/amp_far_rune_knockon/tdep_ko_amp-far.4.3_short_test.ps
    expire_in: 1 week
  dependencies:
  - build:centos7
