comm.h:     1  denfl,  !In common, for degugging
Binary file abchief.o matches
Binary file achief1.o matches
Binary file achiefn.o matches
Binary file aclear.o matches
Binary file ainalloc.o matches
Binary file aindflt1.o matches
Binary file aingeom.o matches
Binary file ainitial.o matches
Binary file ainpla.o matches
Binary file ainplt.o matches
Binary file ainpltpa.o matches
Binary file ainsetpa.o matches
Binary file ainsetva.o matches
Binary file ainspec.o matches
Binary file ainvnorm.o matches
Binary file ampfar.o matches
Binary file bavdens.o matches
Binary file bavgmax.o matches
Binary file baviorbt.o matches
Binary file bsl.o matches
Binary file bsu.o matches
Binary file cfpcoefc.o matches
Binary file cfpcoefn.o matches
Binary file cfpcoefr.o matches
Binary file cfpgamma.o matches
Binary file cfpleg.o matches
Binary file cfpsymt.o matches
Binary file coefefad.o matches
Binary file coefefld.o matches
Binary file coefegad.o matches
Binary file coeffpad.o matches
Binary file coefload.o matches
Binary file coefmidt.o matches
Binary file coefmidv.o matches
Binary file coefrfad.o matches
Binary file coefstup.o matches
Binary file coefsyad.o matches
Binary file coefwti.o matches
Binary file coefwtj.o matches
comm.h:     1  denfl,  !In common, for degugging
Binary file diagdens.o matches
Binary file diagdenz.o matches
Binary file diagentr.o matches
Binary file diagescl.o matches
Binary file diaggnde2.o matches
Binary file diaggnde.o matches
Binary file diagimpd.o matches
Binary file diag.o matches
Binary file diagscal.o matches
Binary file diagwrng.o matches
Binary file diagxswt.o matches
Binary file diagxswx.o matches
Binary file dsk_gr.o matches
Binary file dskout.o matches
Binary file efield.o matches
Binary file eflditer.o matches
Binary file eqalloc.o matches
Binary file eqcoord.o matches
Binary file eqelpse.o matches
Binary file eqflxavg.o matches
Binary file eqfndpsi.o matches
Binary file eqfninv.o matches
Binary file eqfn.o matches
Binary file eqfpsi.o matches
Binary file eqinitl.o matches
Binary file eqjac.o matches
Binary file eqonovrp.o matches
Binary file eqorbit.o matches
Binary file eqrhopsi.o matches
Binary file eqrhs.o matches
Binary file eqtopeol.o matches
Binary file equilib.o matches
Binary file eqvolpsi.o matches
Binary file exsweep.o matches
Binary file exsweept.o matches
Binary file exsweepx.o matches
Binary file finit.o matches
fle.f:         denfl=0.0
fle.f:      denfl=denfl+dz(lp,ll)/bbpsi(lp,ll)*den_of_s2(lp)/zmaxpsi(ll)
fle.f:         denfl=0.0
fle.f:      denfl=denfl+(dz(lp,lr_)/bbpsi(lp,lr_))*den_of_s1(lp)/zmaxpsi(lr_)
Binary file fle.o matches
Binary file flxfn.o matches
Binary file freyasou.o matches
Binary file frinitz.o matches
Binary file frplteq.o matches
Binary file frsmooth.o matches
Binary file frstup.o matches
Binary file frwrong.o matches
Binary file impavnc0.o matches
Binary file impchk.o matches
Binary file it3dalloc.o matches
Binary file losscone.o matches
Binary file lossegy.o matches
Binary file lossorbm.o matches
Binary file losstor.o matches
Binary file micgmbnd.o matches
Binary file micgnbnd.o matches
Binary file micxinil.o matches
Binary file micxinim.o matches
Binary file micxinit.o matches
Binary file micxiniz.o matches
Binary file netcdfrf.o matches
netcdfrw2.f:      vid=ncvdef2(ncid,'denfl',NCDOUBLE,2,r_dims,istatus)
netcdfrw2.f:         istatus= NF_INQ_VARID(ncid,'denfl',vid)  !-YuP: NetCDF-f77 get vid
netcdfrw2.f:         call ncvpt_doubl2(ncid,vid,start(3),r_count,denfl,istatus)
netcdfrw2.f:      istatus= NF_INQ_VARID(ncid,'denfl',vid)  !-YuP: NetCDF-f77 get vid
netcdfrw2.f:         call ncvpt_doubl2(ncid,vid,start(3),r_count,denfl,istatus)
Binary file netcdfrw2.o matches
Binary file ntdstore.o matches
Binary file ntloop.o matches
Binary file pltcont.o matches
Binary file pltdf.o matches
Binary file pltdnz.o matches
Binary file pltelec.o matches
Binary file pltendn.o matches
Binary file pltends.o matches
Binary file pltfluxs.o matches
Binary file pltfofvv.o matches
Binary file pltfvsv.o matches
Binary file pltinit.o matches
Binary file pltlosc.o matches
Binary file pltmain.o matches
Binary file pltpower.o matches
Binary file pltprppr.o matches
Binary file pltrstv.o matches
Binary file pltrun.o matches
Binary file pltstrml.o matches
Binary file pltvec.o matches
Binary file pltvflux.o matches
Binary file profaxis.o matches
Binary file profiles.o matches
Binary file prpprctr.o matches
Binary file prppr.o matches
Binary file psif.o matches
Binary file psifp.o matches
Binary file psifppy.o matches
Binary file psifpy.o matches
Binary file psiinv.o matches
Binary file rdc_bplt.o matches
Binary file rdc_multi.o matches
Binary file restcon.o matches
Binary file resthks.o matches
Binary file restvty.o matches
Binary file rf.o matches
Binary file sigalloc.o matches
Binary file siggy.o matches
Binary file sigmax.o matches
Binary file sigmaxwl.o matches
Binary file sigsetup.o matches
Binary file sigv5d.o matches
Binary file sigv.o matches
Binary file soucrit.o matches
Binary file sounorm.o matches
Binary file soup0.o matches
Binary file souplt.o matches
Binary file soup.o matches
Binary file sourc0.o matches
Binary file sourcee.o matches
Binary file sourcef.o matches
Binary file sourceko.o matches
Binary file sourcpwr.o matches
Binary file synchrad.o matches
Binary file tdboothi.o matches
Binary file tdbootst.o matches
Binary file tdchief.o matches
Binary file tddiag.o matches
Binary file tdeqdsk.o matches
Binary file tdfinterp.o matches
Binary file tdinitl.o matches
Binary file tdinlegw.o matches
Binary file tdnflxs.o matches
Binary file tdnpa0.o matches
Binary file tdnpadiag.o matches
Binary file tdnpalam.o matches
Binary file tdnpa.o matches
Binary file tdoutput.o matches
Binary file tdplteq.o matches
Binary file tdpltjop.o matches
Binary file tdpltmne.o matches
Binary file tdreadf.o matches
Binary file tdrmshst.o matches
Binary file tdsetnpa.o matches
Binary file tdsetsxr.o matches
Binary file tdstin.o matches
Binary file tdsxr0.o matches
Binary file tdsxray.o matches
Binary file tdsxr.o matches
Binary file tdsxrplt.o matches
Binary file tdtloop.o matches
Binary file tdtoarad.o matches
Binary file tdtoaray.o matches
Binary file tdtraloc.o matches
Binary file tdtranspn.o matches
Binary file tdtransp.o matches
Binary file tdtravct.o matches
Binary file tdtrchkd.o matches
Binary file tdtrchk.o matches
Binary file tdtrcon.o matches
Binary file tdtrdfus.o matches
Binary file tdtrfcop.o matches
Binary file tdtrflg.o matches
Binary file tdtrflx.o matches
Binary file tdtrmuy.o matches
Binary file tdtrrsou.o matches
Binary file tdtrrtov2.o matches
Binary file tdtrrtov.o matches
Binary file tdtrsavf.o matches
Binary file tdtrsym.o matches
Binary file tdtrvint.o matches
Binary file tdtrvsou.o matches
Binary file tdtrvtor2.o matches
Binary file tdtrvtor3.o matches
Binary file tdtrvtor.o matches
Binary file tdtrwtl.o matches
Binary file tdtry.o matches
Binary file tdtscinp.o matches
Binary file tdtscout.o matches
Binary file tdwritef.o matches
Binary file tdxinitl.o matches
Binary file urfalloc.o matches
Binary file urfavg.o matches
Binary file urfb0.o matches
Binary file urfbes.o matches
Binary file urfbplt.o matches
Binary file urfchief.o matches
Binary file urfdamp0.o matches
Binary file urfdamp1.o matches
Binary file urfdamp2.o matches
Binary file urfdampa.o matches
Binary file urfdout.o matches
Binary file urfedge.o matches
Binary file urffflx.o matches
Binary file urfinitl.o matches
Binary file urfmidv.o matches
Binary file urfpack.o matches
Binary file urfrays.o matches
Binary file urfread_.o matches
Binary file urfread.o matches
Binary file urfsetup.o matches
Binary file urfwrite_.o matches
Binary file urfwrite.o matches
Binary file vlfalloc.o matches
Binary file vlfbplt.o matches
Binary file vlf.o matches
Binary file vlfsetup.o matches
Binary file vlhbplt.o matches
Binary file vlhd.o matches
Binary file vlh.o matches
Binary file wpalloc.o matches
Binary file wparsou.o matches
Binary file wpavg.o matches
Binary file wpbdry.o matches
Binary file wpcheck.o matches
Binary file wpchgdy.o matches
Binary file wpcthta.o matches
Binary file wpelecf.o matches
Binary file wpinitl.o matches
Binary file wploweq.o matches
Binary file wpmshchk.o matches
Binary file wpsavf.o matches
Binary file wptrafx.o matches
Binary file wptramu.o matches
Binary file wptrmuy.o matches
Binary file wpvptb.o matches
Binary file wpwrng.o matches
Binary file xcql3d_gfortran64 matches
Binary file xcql3d_gfortran64_debug_BOUNDS-CHECK matches
