#!/bin/bash
# July 17, 2007
# Edit following line to point to genray executable to be tested.
#XGENRAY='/home/bobh/cql3d/genray/genray_cvs/code/gr_v6_070720/xgenray'
#XGENRAY='/home/bobh/cql3d/genray/genray_cvs/code/genray_v6-0/xgenray'
#XGENRAY='/home/bobh/cql3d/genray/genray_cvs/code/gr070121/xgenray'
#XGENRAY='/home/bobh/cql3d/genray/genray_cvs/code/gr061106/xgenray'
#XGENRAY='/home/bobh/cql3d/genray/genray_cvs/code/gr060211/xgenray'
#XGENRAY='/home/bobh/cql3d/genray/genray_cvs/code/gr060421/xgenray'
#XGENRAY='/home/bobh/cql3d/genray/genray_cvs/code/gr_v6_070720_25_1/xgenray'
#XGENRAY='/home/bobh/cql3d/genray/genray_cvs/code/genray_v6-1_070726/xgenray'
#XGENRAY='/home/bobh/cql3d/genray/genray_cvs/code/genray_v6-3_070801/xgenray'
#XGENRAY='/home/bobh/cql3d/genray/genray_cvs/code/genray_v7-8_080801/xgenray'
#XGENRAY='/home/bobh/cql3d/genray/genray_cvs/code/genray_v7-11_081007/xgenray'
#XGENRAY='/home/bobh/cql3d/genray/genray_cvs/code/gr081202/xgenray'
#XGENRAY='/home/bobh/cql3d/genray/genray_cvs/code/genray_v7-17_090527/xgenray_nowrite'
#XGENRAY='/home/bobh/cql3d/genray/genray_cvs/code/gr090901/xgenray_nowrite'
XGENRAY='/home/bobh/cql3d/genray/genray_cvs/code/gr090903_090921/xgenray_debug_BOUND_CHECK'
XGENRAY='/home/bobh/cql3d/genray/genray_cvs/code/genray_cswim_svn/trunk/xgenray'
XGENRAY='/home/bobh/cql3d/genray/genray_cvs/code/genray_cswim_svn/trunk/xgenray_nowrite'

mkdir test1
cp genray.dat_SS_Xmode_180_emission test1/genray.dat
cp Scen4_bn2.57_129x129 test1/
cp *.in xdraw.ini idl_emission_spectrum_colorbar.pro test1/
cd test1/
time $XGENRAY > log_test1      #1m30s on bob8  (1m48s, compx1 w bounds-check)
rm  con1 eps* genray.doc gr3d* *.sap zrn.dat
xdraw genr &
cd ..
cp genray.bin_test1 genray.bin
xdraw genr &
cd test1
xdraw em &
cd ..
cp emis.bin_test1 emis.bin
xdraw em &

#gs xdraw_genr_SS_Xmode_180_emission.ps&
#gs xdraw_em_SS_Xmode_180_emission.ps&
#echo "test1: Compare results with xdraw_genr_SS_Xmode_180_emission.ps and xdraw_em_SS_Xmode_180_emission.ps"
sleep 10


mkdir test2
cp genray.dat_HPRT_test_case_061219 test2/genray.dat
cp equilib.dat_HPRT_test_case_061219 drawgenr.in test2/
cd test2/
time $XGENRAY > log_test2    #3.04s on compx1
rm  con1 eps* genray.doc gr3d* *.sap zrn.dat
xdraw genr &
cd ..
cp genray.bin_test2 genray.bin
xdraw genr &
#echo "test2: Compare results with idl_105830p193r1.bob_GR030417.4_gr061120.ps"

mkdir test3
cp genray.dat_113544.00325_mod test3/genray.dat
cp g113544.00325_mod drawgenr.in drawem.in test3/
cd test3/
time $XGENRAY > log_test3    #2m59s on compx1 (3m23s w bounds-check)
rm  con1 eps* genray.doc gr3d* *.sap zrn.dat
xdraw genr &
cd ..
cp genray.bin_test3 genray.bin
xdraw genr &
cd test3
xdraw em &
cd ..
cp emis.bin_test3 emis.bin
xdraw em &
#cd ..
#echo "test3: Compare results with emis.bin_113544.00325_mod and genray.bin_113544.00325_mod"


mkdir test4
cp genray.dat_GT_PoP2005_i_ox=1.1_updtd test4/genray.dat
cp g113544.00325_mod drawgenr.in test4/
cd test4/
time $XGENRAY > log_test4    #13.2s on compx1
emacs ECcone_optimal.dat &
cd ..
emacs ECcone_optimal.dat &
echo "test4: Compare output text files ECcone_optimal.dat"

mkdir test4.1
cp genray.dat_GT_PoP2005_id6_i_ox2_090720 test4.1/genray.dat
cp g113544.00325_mod drawgenr.in drawfreqelec.in test4.1/
cd test4.1/
time $XGENRAY > log_test4.1    #27s on compx1
xdraw genr &
cd ..
echo "test4.1: Compare genray.bin_test4.1 with test4/genray.bin using xdraw"
cp genray.bin_test4.1 genray.bin
xdraw genr &



mkdir test5
cp genray.dat_CANONICAL_2004_ITER_TEST_one_ray  test5/genray.dat
cp  g521022.01000 drawgenr.in test5/
cd test5/
time $XGENRAY > log_test5    #1.6s on compx1
xdraw genr &
cd ..
echo "test5: Compare genray.bin_CANONICAL_2004_ITER_TEST_one_ray with test5/genray.bin using xdraw"
cp genray.bin_test5 genray.bin
xdraw genr &


mkdir test5.1
cp genray.dat_id10iabsorp1  test5.1/genray.dat
cp  g521022.01000 drawgenr.in test5.1/
cd test5.1/
time $XGENRAY > log_test5.1    #1m52s on compx1
xdraw genr &
cd ..
echo "test5.1: Compare  genray.bin_id10iabsorp1 with test5.1/genray.bin using xdraw"
cp genray.bin_test5.1 genray.bin
xdraw genr &


mkdir test6
cp genray.dat_shot106270_multi_ray_multi_cone test6/genray.dat
cp g106270.02500 drawgenr.in test6/
cd test6/
time $XGENRAY > log_test6    #15.7s on compx1
xdraw genr &
cd ..
echo "test6: Compare genray.bin_shot106270 with test6/genray.bin using xdraw"
cp genray.bin_test6 genray.bin
xdraw genr &


mkdir test7
cp genray.in_CMod_LH_edge  test7/genray.in
cp g1060728011.01100 drawgenr.in test7/
cd test7/
time $XGENRAY > log_test7    #1m54s on compx1 w xgenr_nw
xdraw genr &
cd ..
echo "test7: Compare genray.bin_CMod_LH_edge with test7/genray.bin using xdraw"
cp genray.bin_test7 genray.bin
xdraw genr &


mkdir test8
cp genray.dat_EC_ITER_Central_CD  test8/genray.dat
cp  equilib.dat_EC_ITER_Central_CD test8/equilib.dat
cp drawonet1.in test8
cd test8/
time $XGENRAY > log_test8    #21.2 min on compx1 w xgenr_nw
#                            #13.6 secs if use already computed adj files.
xdraw onet1 &
cd ..
echo "test8: Compare CD with Prater_NF2008_Fig12.pdf and EC_ITER_Central_CD.ps (prior)"
cp onetwo1.bin_EC_ITER_Central_CD onetwo1.bin
xdraw onet1 &
acroread Prater_NF2008_Fig12.pdf &

#rm -rf test1 test2 test3 test4 test5 test5.1 test6 test7





echo "After finishing viewing results, can remove all subdirectories with a:"
echo  "rm -rf test1 test2 test3 test4 test5 test5.1 test6 test7 test8 emis.bin genray.bin"