c
c
      subroutine urfread
      use param_mod
      use cqcomm_mod
      use netcdfrf_mod, only : netcdfrf
      implicit integer (i-n), real*8 (a-h,o-z)

c.......................................................................
c     This routine reads disk files generated by ray tracing codes,
c     in two possible formats specified by rfread="netcdf" or "text".
c     
c     For rf wave types with any of nharms(k),k=1,mrf that are 
c     equal to 0, then nharms(k) is set equal to 1, and
c     nharm1(k) is obtained from the ray data file.
c
c     First, ray data is read for each wave type.
c     [Each wave "type" is read from its own ray data file.]
c     Then ray data is copied to additional ray data sets for
c     cases where nharms(k).gt.1.
c.......................................................................

CMPIINSERT_INCLUDE


CMPIINSERT_IF_RANK_EQ_0

      krf=0  !  Counter for wave types.
c     irftype (0 for old input method, 1 for new) is dtrmnd in urfinitl.

      if (irftype.eq.0) then    !Old type input of wave type

      if (ech.eq."enabled") then
         krf=krf+1
         if (rfread.eq."netcdf") then
            call netcdfrf(2,krf)
         else
            open(unit=23,file='rayech',status='old',IOSTAT=io1)
            if (io1.eq.0) then
               call urfread_(krf,23)
               close(unit=23)
            else
               WRITE(*,*)'urfread: check that "rayech" file is present'
               stop
            endif
         endif
         if (nharms(krf).eq.0) then
            nharms(krf)=1
            nharm1(krf)=nharm(krf)   !nharm(krf) read in from ray data.
                                     !This option is for backwards
                                     !compatibility.
         endif
      endif
      if (fw.eq."enabled") then
         krf=krf+1
         if (rfread.eq."netcdf") then
            call netcdfrf(2,krf)
         else
            open(unit=24,file='rayfw',status='old',IOSTAT=io1)
            if (io1.eq.0) then
               call urfread_(krf,24)
               close(unit=24)
            else
               write(*,*)'urfread: check that "rayfw" file is present'
               stop
            endif
         endif
         if (nharms(krf).eq.0) then
            nharms(krf)=1
            nharm1(krf)=nharm(krf)   !nharm(krf) read in from ray data.
         endif
      endif
      if (lh.eq."enabled") then
         krf=krf+1
         if (rfread.eq."netcdf") then
            call netcdfrf(2,krf)
         else
            open(unit=20,file='raylh',status='old',IOSTAT=io1)
            if (io1.eq.0) then
               call urfread_(krf,20)
               close(unit=20)
            else
               write(*,*)'urfread: check that "raylh" file is present'
               stop
            endif
         endif
         if(partner.eq.'lsc') then
            do is=1,nrayelt(iray,krf)
               wnpar(is,iray,krf)=-wnpar(is,iray,krf)
            enddo
         endif
         if (nharms(krf).eq.0) then
            nharms(krf)=1
            nharm1(krf)=nharm(krf)   !nharm(krf) read in from ray data.
         endif
      endif

      endif   ! on irftype.eq.0

      if (irftype.eq.1) then     !New, more general input of wave types.

         do krf=1,mrf
            if (rftype(krf).eq."ec") then
cBH080911         krf=krf+1
cBH080911         Move krf down.
               call netcdfrf(2,krf)
            endif
            if (rftype(krf).eq."fw") then
cBH080911         krf=krf+1
               call netcdfrf(2,krf)
            endif
            if (rftype(krf).eq."lh") then
cBH080911         krf=krf+1
               call netcdfrf(2,krf)
               if(partner.eq.'lsc') then
                  do is=1,nrayelt(iray,krf)
                     wnpar(is,iray,krf)=-wnpar(is,iray,krf)
                  enddo
               endif
            endif
         enddo

      endif  ! on irftype.eq.1
      
CMPIINSERT_ENDIF_RANK


CMPIINSERT_BCAST_NRAYN
CMPIINSERT_BCAST_NRAYELTS
CMPIINSERT_BCAST_RAYS_DATA
CMPIINSERT_BARRIER


c.......................................................................
c     irftype indicates old (=0) or new (=1) rf data input method.
c     If this is a multispecies run, then irftype must .eq.1
c     for input to more than the first species.
c     For irftype.eq.1 .and .ngen.ge.2, determine if multiple
c     ray types are to be applied separately to each species,
c     or if they are the same rays applied simultaneously ("combined")
c     to multiple species.
c     This issue arises when the same ray data in multiple ray input
c     files is to be applied to different general species (ngen.ge.2),
c     but the damping along the rays is due to the combined effect
c     of the relevant general species.
c     Determine this by whether the input files rffile() are
c     the same file, or not (as determined from the 1st two species).
c     (This logic could be readily generalized to a combination of
c     "separate" and "combined" application of damping and diffusion.)
c.......................................................................

c.......................................................................
      !irffile() is indicator whether input rffile() values are
      !separate (.ne.each other), or duplicates for which power absorption
      !is then combined.
      !irffile()="separate"  !Is default.
                          !Apply damping to ray data files either
                          !as "separate" or combined (damping on
                          !more than one species).
                          !"combine1" is first ray file to be combined,
                          !"combine2" is subsequent identical ray files.
c.......................................................................

      do krf=1,mrf
         irffile(krf)="separate"
      enddo
      if (ngen.ge.2) then  !Assume ray files separate if only 1 species.
      do krf=1,mrf
         if (rffile(krf).ne."notset") then  !should be case for krf=1,mrf

            if (krf.eq.1) then
               irffile(krf)="separate"
               if(mrf.gt.1) then
                  if (rffile(krf).eq.rffile(krf+1))
     +                           irffile(krf)="combine1"
               endif

            elseif (krf.gt.1 .and. krf.lt. mrf) then
               irffile(krf)="separate"
               if(rffile(krf).eq.rffile(krf-1)) then
                  irffile(krf)="combine2"
               elseif(rffile(krf).eq.rffile(krf+1)) then
                  irffile(krf)="combine1"
               endif

            elseif (krf.eq.mrf) then
               irffile(krf)="separate"
               if(rffile(krf).eq.rffile(krf-1))
     +                             irffile(krf)="combine2"

            endif  !On krf


            
         endif                  ! on "notset"
      enddo                     ! on krf
      endif                     ! on ngen

c.......................................................................
c
c     Set up table krfn(1:mrfn), points to wave type index for each mode.
c     Set up table irfn(1:mrf), points to the wave mode index of
c       the lowest harmonic for each wave type.
c     Set up nharm(1:mrfn).
c     REMEMBER:
c     mrf is the number of RF types being calculated.
c     mrfn is the number of wave "modes", that is, the sum over
c     wave types of the number of harmonics for each wave type

c     NOTE:  Cannot set these arrays earlier in code because
c            nharm is possibly read above from ray data files,
c            giving value for nharm1.
c
c.......................................................................
      
      kk=0
      do krf=1,mrf
         do kkk=1,nharms(krf)
            kk=kk+1
            krfn(kk)=krf
            if (kkk.eq.1) irfn(krf)=kk
            nharm(kk)=nharm1(krf)+(kkk-1)
         enddo
      enddo

c.......................................................................
c     irfm(1:mrf) is total number of modes for each distinct (i.e., not
c     identical) rffile, irffile(krf)="separate".
c     For "combined" cases (i.e., identical rffile files), it gives
c     total number of modes partially summed over the combined case files.
c.......................................................................


      do krf=1,mrf
         if (irffile(krf).eq."separate") then
            irfm(krf)=nharms(krf)
         elseif (irffile(krf).eq."combine1") then
            irfm(krf)=nharms(krf)
            kkrf=krf
         elseif(irffile(krf).eq."combine2") then
            irfm(kkrf)=irfm(kkrf)+nharms(krf)
            irfm(krf)=irfm(kkrf)
         endif
      enddo



      write(*,*)
      write(*,*)'urfread: mrf = ',mrf
      write(*,*)'urfread: mrfn = ',mrfn
      write(*,*)'urfread: irfn = ',(irfn(krf),krf=1,mrf)
      write(*,*)'urfread: irfm = ',(irfm(krf),krf=1,mrf)
      write(*,*)'urfread: irffile = ',(irffile(krf),krf=1,mrf)
      write(*,*)'urfread: krfn = ',(krfn(krf),krf=1,mrfn)
      write(*,*)'urfread: nharm1 = ',(nharm1(krf),krf=1,mrf)
      write(*,*)'urfread: nharms = ',(nharms(krf),krf=1,mrf)
      write(*,*)'urfread: nharm = ',(nharm(krf),krf=1,mrfn)
         

c     Duplicate ray data in sets nharms(krf) long using the first ray data
c     for each ray type krf, if there is more than one harmonic:
c     Need to do this duplication in reverse order, k=mrfn,1,-1
c     in order not to overwrite data initially stored as krf=1,mrf.

      do k=mrfn,1,-1

         nray(k)=nray(krfn(k))
         freqcy(k)=freqcy(krfn(k))
         omega(k)=omega(krfn(k))
         
         do 30 iray=1,nray(krfn(k))
            nrayelt(iray,k)=nrayelt(iray,krfn(k))
            istarts(iray,k)=istarts(iray,krfn(k))
            call dcopy(nrayelt(iray,k),ws(1,iray,krfn(k)),1,
cBH081106     &         ws(1,iray,k),krfn(k))   Causes big bug when
cBH081106                                krfn(k).ne.1: i.e., neg B0.
     &           ws(1,iray,k),1)
            call dcopy(nrayelt(iray,k),seikon(1,iray,krfn(k)),1,
     &           seikon(1,iray,k),1)
            call dcopy(nrayelt(iray,k),spsi(1,iray,krfn(k)),1,
     &           spsi(1,iray,k),1)
            call dcopy(nrayelt(iray,k),wr(1,iray,krfn(k)),1,
     &           wr(1,iray,k),1)
            call dcopy(nrayelt(iray,k),wphi(1,iray,krfn(k)),1,
     &           wphi(1,iray,k),1)
            call dcopy(nrayelt(iray,k),wz(1,iray,krfn(k)),1,
     &           wz(1,iray,k),1)
            call dcopy(nrayelt(iray,k),wnpar(1,iray,krfn(k)),1,
     &           wnpar(1,iray,k),1)
            call dcopy(nrayelt(iray,k),wnper(1,iray,krfn(k)),1,
     &           wnper(1,iray,k),1)
            call dcopy(nrayelt(iray,k),delpwr(1,iray,krfn(k)),1,
     &           delpwr(1,iray,k),1)
            call dcopy(nrayelt(iray,k),sdpwr(1,iray,krfn(k)),1,
     &           sdpwr(1,iray,k),1)
            call dcopy(nrayelt(iray,k),wdnpar(1,iray,krfn(k)),1,
     &           wdnpar(1,iray,k),1)
            call dcopy(nrayelt(iray,k),fluxn(1,iray,krfn(k)),1,
     &           fluxn(1,iray,k),1)
            call dcopy(nrayelt(iray,k),sbtot(1,iray,krfn(k)),1,
     &           sbtot(1,iray,k),1)
            call dcopy(nrayelt(iray,k),sene(1,iray,krfn(k)),1,
     &           sene(1,iray,k),1)
            call dcopy(nrayelt(iray,k),salphac(1,iray,krfn(k)),1,
     &           salphac(1,iray,k),1)
            call dcopy(nrayelt(iray,k),salphal(1,iray,krfn(k)),1,
     &           salphal(1,iray,k),1)
            
            do is=1,nrayelt(iray,k)
               cwexde(is,iray,k)=cwexde(is,iray,krfn(k))
               cweyde(is,iray,k)=cweyde(is,iray,krfn(k))
               cwezde(is,iray,k)=cwezde(is,iray,krfn(k))
            enddo
            
 30      continue
      enddo
      
      
c     Temporary printout of some input ray data
c     Dimensioning is nrayelt(nrayn,mrfn),
c                     ws(nrayelts,nrayn,mrfn),etc.
c$$$      write(*,*)'****************************************************'
c$$$      do krf=1,mrfn
c$$$      write(*,*)'urfread:  mode krf = ',krf
c$$$      write(*,*)'nray(krf),nharms(krfn(krf)),freqcy(krf),nharm(krf)',
c$$$     1           nray(krf),nharms(krfn(krf)),freqcy(krf),nharm(krf)
c$$$      write(*,*)'urfread:nrayelt(*,krf)',(nrayelt(i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:ws(1,*,krf)',(ws(1,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:spsi(1,*,krf)',(spsi(1,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:wr(1,*,krf)',(wr(1,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:wz(1,*,krf)',(wz(1,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:wphi(1,*,krf)',(wphi(1,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:wnpar(1,*,krf)',(wnpar(1,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:wnper(1,*,krf)',(wnper(1,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:delpwr(1,*,krf)',
c$$$     1     (delpwr(1,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:sdpwr(1,*,krf)',(sdpwr(1,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:wdnpar(1,*,krf)',
c$$$     1     (wdnpar(1,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:cwexde(1,*,krf)',
c$$$     1     (cwexde(1,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:cweyde(1,*,krf)',
c$$$     1     (cweyde(1,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:cwezde(1,*,krf)',
c$$$     1     (cwezde(1,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:fluxn(1,*,krf)',(fluxn(1,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:sbtot(1,*,krf)',(sbtot(1,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:sene(1,*,krf)',(sene(1,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:salphac(1,*,krf)',
c$$$     1     (salphac(1,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:salphal(1,*,krf)',
c$$$     1     (salphal(1,i,krf),i=1,nray(krf))
c$$$
c$$$      write(*,*)'urfread:ws(2,*,krf)',(ws(2,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:spsi(2,*,krf)',(spsi(2,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:wr(2,*,krf)',(wr(2,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:wz(2,*,krf)',(wz(2,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:wphi(2,*,krf)',(wphi(2,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:wnpar(2,*,krf)',(wnpar(2,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:wnper(2,*,krf)',(wnper(2,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:delpwr(2,*,krf)',
c$$$     1     (delpwr(2,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:sdpwr(2,*,krf)',(sdpwr(2,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:wdnpar(2,*,krf)',
c$$$     1     (wdnpar(2,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:cwexde(2,*,krf)',
c$$$     1     (cwexde(2,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:cweyde(2,*,krf)',
c$$$     1     (cweyde(2,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:cwezde(2,*,krf)',
c$$$     1     (cwezde(2,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:fluxn(2,*,krf)',(fluxn(2,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:sbtot(2,*,krf)',(sbtot(2,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:sene(2,*,krf)',(sene(2,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:salphac(2,*,krf)',
c$$$     1     (salphac(2,i,krf),i=1,nray(krf))
c$$$      write(*,*)'urfread:salphal(2,*,krf)',
c$$$     1     (salphal(2,i,krf),i=1,nray(krf))
c$$$      enddo
c$$$      write(*,*)'****************************************************'
 
      return
      end
